import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);
const STORAGE_KEY = "sillah-language";

const translations = {
  en: {
    common: {
      appName: "Sillah",
      appSubtitle: "صلة - Family Health",
      loading: "Loading...",
      cancel: "Cancel",
      save: "Save",
      close: "Close",
      tryAgain: "Try Again",
      required: "Required",
      optional: "Optional",
      english: "English",
      arabic: "العربية",
      languageToggle: "Switch interface language",
      dismiss: "Dismiss",
      gotIt: "Got it",
      nextStep: "Next step",
    },
    layout: {
      dashboard: "Dashboard",
      myHealth: "My Health",
      alerts: "Alerts",
      medications: "Medications",
      appointments: "Appointments",
      clinics: "Clinics",
      awarenessHub: "Awareness Hub",
      familyTree: "Family Tree",
      riskAssessment: "Risk Assessment",
      patients: "My Patients",
      logout: "Logout",
      menu: "Toggle menu",
    },
    login: {
      title: "Welcome to Sillah (صلة)",
      subtitle: "Login to your account",
      email: "Email Address",
      emailPlaceholder: "your.email@example.com",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Login",
      submitting: "Logging in...",
      noAccount: "Don't have an account?",
      signup: "Sign up",
      phase5: "Open Phase 5 Demo",
      phase5Label: "Working on CS340?",
      onboardingTitle: "First time here?",
      onboardingBody:
        "Use the language switch any time, then sign in to see your dashboard, appointments, and family health tools.",
      onboardingAction: "Create an account",
      emailHelp: "Use the email address linked to your Sillah account.",
      passwordHelp: "Passwords are case-sensitive.",
      validationEmailRequired: "Please enter your email address.",
      validationEmailInvalid: "Enter a valid email address.",
      validationPasswordRequired: "Please enter your password.",
      errorMissing: "Please enter your email and password.",
      errorEmailNotConfirmed:
        "Your email isn’t confirmed yet. Check your inbox and confirm, then try again.",
      errorInvalidCredentials: "Invalid email or password.",
      errorGeneric: "Failed to login. Please try again.",
    },
    signup: {
      title: "Join Sillah (صلة)",
      subtitle: "Create your account",
      role: "I am a",
      patient: "Patient",
      doctor: "Doctor",
      fullName: "Full Name",
      fullNamePlaceholder: "Enter your full name",
      email: "Email Address",
      emailPlaceholder: "your.email@example.com",
      phone: "Phone Number (Optional)",
      phonePlaceholder: "+966 50 123 4567",
      doctorSelect: "Select Your Doctor",
      doctorSelectPlaceholder: "Choose a doctor",
      loadingDoctors: "Loading available doctors...",
      noDoctors:
        "No doctors are available yet. You can still create your patient account now and choose a doctor later.",
      password: "Password",
      confirmPassword: "Confirm Password",
      passwordPlaceholder: "Create a password",
      confirmPasswordPlaceholder: "Re-enter your password",
      submit: "Create Account",
      submitting: "Creating account...",
      haveAccount: "Already have an account?",
      login: "Login",
      onboardingTitle: "Before you create your account",
      onboardingBody:
        "Patients can connect to a doctor during signup when one is available. Doctors can sign up directly and start managing appointments.",
      onboardingAction: "Go to login",
      fullNameHelp: "Enter the name that should appear in your health profile.",
      doctorHelp: "Selecting a doctor helps connect your care team from day one.",
      phoneHelp: "Add a mobile number if you want clinics to reach you easily.",
      validationNameRequired: "Full name is required.",
      validationEmailRequired: "Email is required.",
      validationEmailInvalid: "Enter a valid email address.",
      validationPhoneInvalid: "Use a valid phone number with at least 8 digits.",
      validationPasswordRequired: "Password is required.",
      validationPasswordLength: "Password must be at least 6 characters.",
      validationConfirmRequired: "Please confirm your password.",
      validationPasswordMismatch: "Passwords do not match.",
      validationDoctorRequired: "Please select a doctor.",
      infoCreated: "Account created. Please login to continue.",
      errorRegistered:
        "This email is already registered. Use a different email or remove the existing auth user first.",
      errorGeneric: "Failed to create account.",
    },
    dashboard: {
      welcome: "Welcome back, {{name}}",
      doctorSubtitle: "Healthcare Provider Portal",
      patientSubtitle: "Family Health Portal",
      quickActions: "Quick Actions",
      privacy: "Patient Privacy & Access",
      accountSafety: "Account Safety",
      deleteTitle: "Delete account and all personal data",
      deleteBody:
        "This permanently removes your profile, family records, appointments, medications, alerts, and linked account data.",
      deleteWarning:
        "This action cannot be undone. Type DELETE to confirm before continuing.",
      deletePlaceholder: "Type DELETE",
      deleteButton: "Delete My Account",
      deleteConfirmLabel: "Confirmation text",
      deleteConfirmHelp: "This extra confirmation helps prevent accidental account removal.",
      deleteSuccess: "Your account has been deleted.",
      deleteErrorGeneric: "Failed to delete your account.",
      deleteMismatch: "Type DELETE exactly to continue.",
      deleting: "Deleting account...",
      firstTimeTitle: "Getting started in Sillah",
      firstTimeBody:
        "Use the quick actions below to manage family health records, appointments, and clinic coordination. You can switch between English and Arabic from the top navigation any time.",
    },
    appointments: {
      titlePatient: "My Appointments",
      titleDoctor: "Patient Appointments",
      loading: "Loading appointments...",
      errorSubtitle: "Unable to load appointments",
      errorBody: "Please check your connection or try again later.",
      countPatient: "You have {{count}} appointment{{suffix}}",
      countDoctor: "Managing {{count}} appointment{{suffix}}",
      book: "Book Appointment",
      filters: {
        all: "All",
        upcoming: "Upcoming",
        completed: "Completed",
        cancelled: "Cancelled",
      },
      emptyAllTitle: "No Appointments Yet",
      emptyUpcoming: "No upcoming appointments",
      emptyCompleted: "No completed appointments",
      emptyCancelled: "No cancelled appointments",
      emptyDoctor: "You don't have any appointments scheduled with your patients yet.",
      emptyPatient: "You haven't booked any appointments yet.",
      emptyFiltered: "Try changing the filter to see other appointments.",
      emptyAction: "Book Your First Appointment",
      firstTimeTitle: "How booking works",
      firstTimeBody:
        "Choose a clinic, select a future time, and add a short reason for the visit. Your request will appear as pending until the clinic or doctor confirms it.",
      firstTimeAction: "Book now",
      cancelConfirm: "Are you sure you want to cancel this appointment?",
      cancelSuccess: "Appointment cancelled successfully.",
      cancelFail: "Failed to cancel appointment. Please try again.",
      completeSuccess: "Appointment marked as completed.",
      completeFail: "Failed to complete appointment. Please try again.",
      confirmSuccess: "Appointment confirmed.",
      confirmFallback:
        "Appointment remains pending. Add 'confirmed' or 'scheduled' to the enum to support explicit confirmation.",
      confirmFail: "Failed to confirm appointment. Please try again.",
      patientOnly: "Only patient accounts can book appointments.",
      bookSuccess: "Appointment booked successfully.",
      bookFail: "Failed to book appointment. Please try again.",
      modalTitle: "Book an Appointment",
      clinic: "Select Clinic",
      clinicPlaceholder: "-- Choose a clinic --",
      noClinics:
        "No clinics are available in the database yet. Add rows in `public.clinics` to enable booking.",
      clinicHelp: "Pick the clinic where you want the visit to happen.",
      availableToday: "Available Today",
      availableHelp: "Choose a suggested slot to fill the date and time automatically.",
      date: "Date",
      time: "Time",
      reason: "Reason for Visit",
      reasonPlaceholder: "e.g., Annual checkup, Follow-up",
      reasonHelp: "A short reason helps the care team prepare for your visit.",
      notes: "Additional Notes",
      notesPlaceholder: "Any additional information...",
      notesHelp: "Optional: mention symptoms, concerns, or special instructions.",
      confirmBooking: "Book Appointment",
      validationClinic: "Please choose a clinic.",
      validationDate: "Please choose an appointment date.",
      validationTime: "Please choose an appointment time.",
      validationPast: "Appointment time cannot be in the past.",
      statusPending: "Pending Confirmation",
      statusConfirmed: "Confirmed",
      statusScheduled: "Scheduled",
      statusCompleted: "Completed",
      statusCancelled: "Cancelled",
      reasonLabel: "Reason:",
      notesLabel: "Notes:",
      confirmAppointment: "Confirm Appointment",
      markCompleted: "Mark as Completed",
      cancelTooltip: "Cancel appointment",
    },
    family: {
      title: "Family Health Tree",
      subtitle: "Manage your family members",
      add: "Add Family Member",
      addFirst: "Add Your First Family Member",
      edit: "Edit Family Member",
      emptyTitle: "No Family Members Added Yet",
      emptyText: "Start by adding a family member.",
      searchPlaceholder: "Search by name, relationship, or gender...",
      noMatches: "No matching family members",
      noMatchesBody: "Try a different search term.",
      firstTimeTitle: "Build your family history",
      firstTimeBody:
        "Add close relatives first, then record health details to spot inherited risk patterns more clearly.",
      firstTimeAction: "Add member",
      fullName: "Full Name",
      relationship: "Relationship",
      relationshipPlaceholder: "Select relationship",
      relationshipHelp: "Choose how this family member is related to you.",
      gender: "Gender",
      genderPlaceholder: "Select gender",
      male: "Male",
      female: "Female",
      other: "Other",
      dateOfBirth: "Date of Birth",
      dateOfBirthHelp: "Use the most accurate date you know. It helps estimate family risk correctly.",
      validationName: "Please enter a full name.",
      validationRelationship: "Please select a relationship.",
      validationDateFuture: "Date of birth cannot be in the future.",
      editTooltip: "Edit family member",
      deleteTooltip: "Delete family member",
      genderLabel: "Gender:",
      dobLabel: "Date of Birth:",
      latestCondition: "Latest Condition:",
      diagnosisDate: "Diagnosis Date:",
      unnamed: "Unnamed",
      unknownRelation: "Unknown relation",
    },
    phase5: {
      badge: "CS340 Phase 5 Integration",
      title: "Sillah Phase 5 Demo",
      subtitle:
        "A polished database demo that connects the React interface to the MySQL/Express backend and runs SQL through the application.",
      stackTop: "React UI",
      stackBottom: "MySQL + Express",
      onboardingTitle: "Demo guide",
      onboardingBody:
        "Use the tabs to create sample records, inspect joined data, and run stored query endpoints. Inline messages will point out missing required fields before a request is sent.",
      usersTab: "Users",
      familyTab: "Family Members",
      queriesTab: "Queries",
      usersEyebrow: "CRUD Table",
      usersTitle: "Users",
      usersCopy: "Create sample users, then verify the UI refreshes from the backend.",
      familyEyebrow: "Relational Data",
      familyTitle: "Family Members",
      familyCopy: "Add family-member rows connected to existing users and inspect joined emails.",
      queriesEyebrow: "SQL Showcase",
      queriesTitle: "Queries q01-q40",
      queriesCopy: "Run stored query endpoints and preview the JSON returned by the backend.",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone number",
      userId: "user_id (existing)",
      dateOfBirth: "Date of birth",
      relationship: "Relationship",
      queryId: "Query ID",
      addUser: "Add User",
      addFamilyMember: "Add Family Member",
      runQuery: "Run Query",
      delete: "Delete",
      tryQueries: "Try: q24, q22, q36",
      noUsers: "No users loaded yet.",
      noFamily: "No family members loaded yet.",
      userIdHelp: "Use a user_id from the Users table so the family member can be linked.",
      queryHelp: "Enter a query id from q01 to q40.",
      deleteUserHelp: "Delete this sample user row from the MySQL demo table.",
      deleteFamilyHelp: "Delete this sample family-member row from the MySQL demo table.",
      validationFirstName: "First name is required.",
      validationLastName: "Last name is required.",
      validationEmail: "Enter a valid email address.",
      validationPhone: "Phone number is required.",
      validationUserId: "Enter an existing numeric user_id.",
      validationDate: "Date of birth is required.",
      validationRelationship: "Relationship is required.",
      validationQuery: "Enter a query id like q24.",
      columns: {
        action: "action",
        name: "name",
      },
    },
  },
  ar: {
    common: {
      appName: "صلة",
      appSubtitle: "صلة - صحة العائلة",
      loading: "جاري التحميل...",
      cancel: "إلغاء",
      save: "حفظ",
      close: "إغلاق",
      tryAgain: "حاول مرة أخرى",
      required: "مطلوب",
      optional: "اختياري",
      english: "English",
      arabic: "العربية",
      languageToggle: "تبديل لغة الواجهة",
      dismiss: "إخفاء",
      gotIt: "فهمت",
      nextStep: "الخطوة التالية",
    },
    layout: {
      dashboard: "لوحة التحكم",
      myHealth: "صحتي",
      alerts: "التنبيهات",
      medications: "الأدوية",
      appointments: "المواعيد",
      clinics: "العيادات",
      awarenessHub: "التوعية الصحية",
      familyTree: "شجرة العائلة",
      riskAssessment: "تقييم المخاطر",
      patients: "مرضاي",
      logout: "تسجيل الخروج",
      menu: "فتح القائمة",
    },
    login: {
      title: "مرحباً بك في صلة",
      subtitle: "سجّل الدخول إلى حسابك",
      email: "البريد الإلكتروني",
      emailPlaceholder: "your.email@example.com",
      password: "كلمة المرور",
      passwordPlaceholder: "أدخل كلمة المرور",
      submit: "تسجيل الدخول",
      submitting: "جارٍ تسجيل الدخول...",
      noAccount: "ليس لديك حساب؟",
      signup: "إنشاء حساب",
      phase5: "فتح عرض المرحلة الخامسة",
      phase5Label: "هل تعمل على CS340؟",
      onboardingTitle: "هل هذه أول زيارة لك؟",
      onboardingBody:
        "يمكنك تغيير اللغة في أي وقت، ثم تسجيل الدخول للوصول إلى لوحة التحكم والمواعيد وأدوات صحة العائلة.",
      onboardingAction: "إنشاء حساب",
      emailHelp: "استخدم البريد الإلكتروني المرتبط بحسابك في صلة.",
      passwordHelp: "كلمات المرور حساسة لحالة الأحرف.",
      validationEmailRequired: "يرجى إدخال البريد الإلكتروني.",
      validationEmailInvalid: "أدخل بريداً إلكترونياً صحيحاً.",
      validationPasswordRequired: "يرجى إدخال كلمة المرور.",
      errorMissing: "يرجى إدخال البريد الإلكتروني وكلمة المرور.",
      errorEmailNotConfirmed: "لم يتم تأكيد بريدك الإلكتروني بعد. تحقق من صندوق الوارد ثم حاول مرة أخرى.",
      errorInvalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      errorGeneric: "تعذر تسجيل الدخول. حاول مرة أخرى.",
    },
    signup: {
      title: "انضم إلى صلة",
      subtitle: "أنشئ حسابك",
      role: "أنا",
      patient: "مريض",
      doctor: "طبيب",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "أدخل اسمك الكامل",
      email: "البريد الإلكتروني",
      emailPlaceholder: "your.email@example.com",
      phone: "رقم الجوال (اختياري)",
      phonePlaceholder: "+966 50 123 4567",
      doctorSelect: "اختر طبيبك",
      doctorSelectPlaceholder: "اختر طبيباً",
      loadingDoctors: "جارٍ تحميل الأطباء المتاحين...",
      noDoctors: "لا يوجد أطباء متاحون حالياً. يمكنك إنشاء حساب المريض الآن واختيار الطبيب لاحقاً.",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      passwordPlaceholder: "أنشئ كلمة مرور",
      confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
      submit: "إنشاء الحساب",
      submitting: "جارٍ إنشاء الحساب...",
      haveAccount: "لديك حساب بالفعل؟",
      login: "تسجيل الدخول",
      onboardingTitle: "قبل إنشاء الحساب",
      onboardingBody:
        "يمكن للمريض ربط حسابه بطبيب أثناء التسجيل إذا كان متاحاً. ويمكن للطبيب التسجيل مباشرة والبدء في إدارة المواعيد.",
      onboardingAction: "الذهاب لتسجيل الدخول",
      fullNameHelp: "أدخل الاسم الذي سيظهر في ملفك الصحي.",
      doctorHelp: "اختيار الطبيب يساعد على ربط فريق رعايتك من البداية.",
      phoneHelp: "أضف رقم جوال إذا أردت أن تتواصل معك العيادات بسهولة.",
      validationNameRequired: "الاسم الكامل مطلوب.",
      validationEmailRequired: "البريد الإلكتروني مطلوب.",
      validationEmailInvalid: "أدخل بريداً إلكترونياً صحيحاً.",
      validationPhoneInvalid: "استخدم رقم هاتف صحيحاً يحتوي على 8 أرقام على الأقل.",
      validationPasswordRequired: "كلمة المرور مطلوبة.",
      validationPasswordLength: "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
      validationConfirmRequired: "يرجى تأكيد كلمة المرور.",
      validationPasswordMismatch: "كلمتا المرور غير متطابقتين.",
      validationDoctorRequired: "يرجى اختيار طبيب.",
      infoCreated: "تم إنشاء الحساب. يرجى تسجيل الدخول للمتابعة.",
      errorRegistered: "هذا البريد الإلكتروني مسجل بالفعل. استخدم بريداً آخر أو احذف المستخدم الحالي أولاً.",
      errorGeneric: "تعذر إنشاء الحساب.",
    },
    dashboard: {
      welcome: "مرحباً بعودتك، {{name}}",
      doctorSubtitle: "بوابة مقدم الرعاية الصحية",
      patientSubtitle: "بوابة صحة العائلة",
      quickActions: "إجراءات سريعة",
      privacy: "خصوصية المريض والوصول",
      accountSafety: "أمان الحساب",
      deleteTitle: "حذف الحساب وجميع البيانات الشخصية",
      deleteBody:
        "سيؤدي هذا إلى حذف ملفك الشخصي وسجلات العائلة والمواعيد والأدوية والتنبيهات والبيانات المرتبطة بالحساب بشكل نهائي.",
      deleteWarning:
        "لا يمكن التراجع عن هذا الإجراء. اكتب DELETE للتأكيد قبل المتابعة.",
      deletePlaceholder: "اكتب DELETE",
      deleteButton: "حذف حسابي",
      deleteConfirmLabel: "نص التأكيد",
      deleteConfirmHelp: "هذا التأكيد الإضافي يساعد على منع حذف الحساب عن طريق الخطأ.",
      deleteSuccess: "تم حذف حسابك.",
      deleteErrorGeneric: "تعذر حذف الحساب.",
      deleteMismatch: "اكتب DELETE تماماً للمتابعة.",
      deleting: "جارٍ حذف الحساب...",
      firstTimeTitle: "البدء في صلة",
      firstTimeBody:
        "استخدم الإجراءات السريعة لإدارة السجل الصحي العائلي والمواعيد والتنسيق مع العيادات. يمكنك التبديل بين العربية والإنجليزية من أعلى الصفحة في أي وقت.",
    },
    appointments: {
      titlePatient: "مواعيدي",
      titleDoctor: "مواعيد المرضى",
      loading: "جارٍ تحميل المواعيد...",
      errorSubtitle: "تعذر تحميل المواعيد",
      errorBody: "يرجى التحقق من الاتصال أو المحاولة لاحقاً.",
      countPatient: "لديك {{count}} موعد{{suffix}}",
      countDoctor: "تدير {{count}} موعد{{suffix}}",
      book: "حجز موعد",
      filters: {
        all: "الكل",
        upcoming: "القادمة",
        completed: "المكتملة",
        cancelled: "الملغاة",
      },
      emptyAllTitle: "لا توجد مواعيد بعد",
      emptyUpcoming: "لا توجد مواعيد قادمة",
      emptyCompleted: "لا توجد مواعيد مكتملة",
      emptyCancelled: "لا توجد مواعيد ملغاة",
      emptyDoctor: "لا توجد لديك مواعيد مجدولة مع مرضاك حتى الآن.",
      emptyPatient: "لم تقم بحجز أي موعد بعد.",
      emptyFiltered: "جرّب تغيير الفلتر لرؤية مواعيد أخرى.",
      emptyAction: "احجز أول موعد لك",
      firstTimeTitle: "كيف يعمل الحجز",
      firstTimeBody:
        "اختر العيادة ثم حدّد وقتاً مستقبلياً وأضف سبباً مختصراً للزيارة. سيظهر الطلب بحالة معلّق حتى يتم تأكيده من الطبيب أو العيادة.",
      firstTimeAction: "احجز الآن",
      cancelConfirm: "هل أنت متأكد من رغبتك في إلغاء هذا الموعد؟",
      cancelSuccess: "تم إلغاء الموعد بنجاح.",
      cancelFail: "تعذر إلغاء الموعد. حاول مرة أخرى.",
      completeSuccess: "تم تحديد الموعد كمكتمل.",
      completeFail: "تعذر إكمال الموعد. حاول مرة أخرى.",
      confirmSuccess: "تم تأكيد الموعد.",
      confirmFallback: "لا يزال الموعد معلقاً. أضف القيمة المناسبة في الحقل لدعم التأكيد الصريح.",
      confirmFail: "تعذر تأكيد الموعد. حاول مرة أخرى.",
      patientOnly: "حسابات المرضى فقط يمكنها حجز المواعيد.",
      bookSuccess: "تم حجز الموعد بنجاح.",
      bookFail: "تعذر حجز الموعد. حاول مرة أخرى.",
      modalTitle: "حجز موعد",
      clinic: "اختر العيادة",
      clinicPlaceholder: "-- اختر عيادة --",
      noClinics: "لا توجد عيادات متاحة حالياً في قاعدة البيانات. أضف بيانات العيادات لتفعيل الحجز.",
      clinicHelp: "اختر العيادة التي تريد أن تتم فيها الزيارة.",
      availableToday: "الأوقات المتاحة اليوم",
      availableHelp: "اختيار وقت مقترح يملأ التاريخ والوقت تلقائياً.",
      date: "التاريخ",
      time: "الوقت",
      reason: "سبب الزيارة",
      reasonPlaceholder: "مثال: فحص سنوي، متابعة",
      reasonHelp: "سبب مختصر يساعد فريق الرعاية على الاستعداد للزيارة.",
      notes: "ملاحظات إضافية",
      notesPlaceholder: "أي معلومات إضافية...",
      notesHelp: "اختياري: اذكر الأعراض أو المخاوف أو التعليمات الخاصة.",
      confirmBooking: "حجز الموعد",
      validationClinic: "يرجى اختيار عيادة.",
      validationDate: "يرجى اختيار تاريخ الموعد.",
      validationTime: "يرجى اختيار وقت الموعد.",
      validationPast: "لا يمكن أن يكون الموعد في وقت سابق.",
      statusPending: "بانتظار التأكيد",
      statusConfirmed: "مؤكد",
      statusScheduled: "مجدول",
      statusCompleted: "مكتمل",
      statusCancelled: "ملغي",
      reasonLabel: "السبب:",
      notesLabel: "الملاحظات:",
      confirmAppointment: "تأكيد الموعد",
      markCompleted: "تحديد كمكتمل",
      cancelTooltip: "إلغاء الموعد",
    },
    family: {
      title: "شجرة صحة العائلة",
      subtitle: "إدارة أفراد العائلة",
      add: "إضافة فرد",
      addFirst: "أضف أول فرد من العائلة",
      edit: "تعديل فرد العائلة",
      emptyTitle: "لم تتم إضافة أفراد للعائلة بعد",
      emptyText: "ابدأ بإضافة أحد أفراد العائلة.",
      searchPlaceholder: "ابحث بالاسم أو القرابة أو الجنس...",
      noMatches: "لا توجد نتائج مطابقة",
      noMatchesBody: "جرّب كلمة بحث مختلفة.",
      firstTimeTitle: "ابنِ التاريخ الصحي للعائلة",
      firstTimeBody:
        "ابدأ بإضافة الأقارب الأقرب أولاً، ثم سجّل التفاصيل الصحية لتسهيل اكتشاف أنماط المخاطر الوراثية.",
      firstTimeAction: "إضافة فرد",
      fullName: "الاسم الكامل",
      relationship: "صلة القرابة",
      relationshipPlaceholder: "اختر صلة القرابة",
      relationshipHelp: "اختر كيف يرتبط هذا الفرد بك.",
      gender: "الجنس",
      genderPlaceholder: "اختر الجنس",
      male: "ذكر",
      female: "أنثى",
      other: "آخر",
      dateOfBirth: "تاريخ الميلاد",
      dateOfBirthHelp: "استخدم أدق تاريخ تعرفه لأنه يساعد في تقدير المخاطر العائلية.",
      validationName: "يرجى إدخال الاسم الكامل.",
      validationRelationship: "يرجى اختيار صلة القرابة.",
      validationDateFuture: "لا يمكن أن يكون تاريخ الميلاد في المستقبل.",
      editTooltip: "تعديل فرد العائلة",
      deleteTooltip: "حذف فرد العائلة",
      genderLabel: "الجنس:",
      dobLabel: "تاريخ الميلاد:",
      latestCondition: "آخر حالة:",
      diagnosisDate: "تاريخ التشخيص:",
      unnamed: "بدون اسم",
      unknownRelation: "صلة غير معروفة",
    },
    phase5: {
      badge: "تكامل المرحلة الخامسة CS340",
      title: "عرض صلة للمرحلة الخامسة",
      subtitle:
        "عرض قاعدة بيانات بتصميم محسّن يربط واجهة React بخادم MySQL/Express ويشغّل أوامر SQL من خلال التطبيق.",
      stackTop: "واجهة React",
      stackBottom: "MySQL + Express",
      onboardingTitle: "دليل العرض",
      onboardingBody:
        "استخدم التبويبات لإنشاء سجلات تجريبية، وفحص البيانات المرتبطة، وتشغيل نقاط نهاية الاستعلامات. ستظهر رسائل داخلية عند نقص الحقول المطلوبة قبل إرسال الطلب.",
      usersTab: "المستخدمون",
      familyTab: "أفراد العائلة",
      queriesTab: "الاستعلامات",
      usersEyebrow: "جدول CRUD",
      usersTitle: "المستخدمون",
      usersCopy: "أنشئ مستخدمين تجريبيين ثم تحقق من تحديث الواجهة من الخادم.",
      familyEyebrow: "بيانات مترابطة",
      familyTitle: "أفراد العائلة",
      familyCopy: "أضف سجلات لأفراد العائلة مرتبطة بمستخدمين موجودين وافحص البريد المرتبط.",
      queriesEyebrow: "عرض SQL",
      queriesTitle: "الاستعلامات q01-q40",
      queriesCopy: "شغّل نقاط نهاية الاستعلامات المخزنة واستعرض JSON العائد من الخادم.",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      phone: "رقم الجوال",
      userId: "معرّف المستخدم الحالي",
      dateOfBirth: "تاريخ الميلاد",
      relationship: "صلة القرابة",
      queryId: "معرّف الاستعلام",
      addUser: "إضافة مستخدم",
      addFamilyMember: "إضافة فرد عائلة",
      runQuery: "تشغيل الاستعلام",
      delete: "حذف",
      tryQueries: "جرّب: q24, q22, q36",
      noUsers: "لم يتم تحميل أي مستخدمين بعد.",
      noFamily: "لم يتم تحميل أي أفراد عائلة بعد.",
      userIdHelp: "استخدم user_id من جدول المستخدمين لربط فرد العائلة.",
      queryHelp: "أدخل معرّف استعلام من q01 إلى q40.",
      deleteUserHelp: "حذف هذا المستخدم التجريبي من جدول MySQL.",
      deleteFamilyHelp: "حذف سجل فرد العائلة التجريبي من جدول MySQL.",
      validationFirstName: "الاسم الأول مطلوب.",
      validationLastName: "اسم العائلة مطلوب.",
      validationEmail: "أدخل بريداً إلكترونياً صحيحاً.",
      validationPhone: "رقم الجوال مطلوب.",
      validationUserId: "أدخل رقم user_id موجود.",
      validationDate: "تاريخ الميلاد مطلوب.",
      validationRelationship: "صلة القرابة مطلوبة.",
      validationQuery: "أدخل معرّف استعلام مثل q24.",
      columns: {
        action: "الإجراء",
        name: "الاسم",
      },
    },
  },
};

function getByPath(object, path) {
  return path.split(".").reduce((acc, part) => (acc && acc[part] !== undefined ? acc[part] : undefined), object);
}

function applyParams(template, params) {
  if (!params) return template;
  return Object.entries(params).reduce(
    (result, [key, value]) => result.replaceAll(`{{${key}}}`, String(value)),
    template
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || "en");

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.body.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo(() => {
    const t = (path, params, fallback = path) => {
      const entry =
        getByPath(translations[language], path) ??
        getByPath(translations.en, path);

      if (typeof entry !== "string") return fallback;
      return applyParams(entry, params);
    };

    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "ar" : "en")),
      isArabic: language === "ar",
      dir: language === "ar" ? "rtl" : "ltr",
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
